version: '3.3'

networks:
  my_network_bridge:
    driver: bridge
services:
  app:
    image: dps:latest
    restart: always
    environment:
      STORE_HOST: db
      STORE_USER: root
      STORE_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "8080:8080"
    networks:
      - my_network_bridge
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - ./sqls/init_dpsmysql.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network_bridge

