// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: dps_server.proto

package dps_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTopicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicName string `protobuf:"bytes,1,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
}

func (x *CreateTopicReq) Reset() {
	*x = CreateTopicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicReq) ProtoMessage() {}

func (x *CreateTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicReq.ProtoReflect.Descriptor instead.
func (*CreateTopicReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicReq) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

type CommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *CommonRes) Reset() {
	*x = CommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRes) ProtoMessage() {}

func (x *CommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRes.ProtoReflect.Descriptor instead.
func (*CommonRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{1}
}

func (x *CommonRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommonRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{2}
}

func (x *PublishReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type PublishRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *PublishRes) Reset() {
	*x = PublishRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRes) ProtoMessage() {}

func (x *PublishRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRes.ProtoReflect.Descriptor instead.
func (*PublishRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{3}
}

func (x *PublishRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PublishRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic               string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	Priority            int32  `protobuf:"varint,2,opt,name=Priority,proto3" json:"Priority,omitempty"`         // Lower number mean higher priority
	Payload             []byte `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`            // immutable binary blob. Feel free to put what ever u want
	Metadata            []byte `protobuf:"bytes,4,opt,name=Metadata,proto3" json:"Metadata,omitempty"`          // mutable binary blob. Feel free to put what ever u want
	DeliverAfter        int32  `protobuf:"varint,5,opt,name=DeliverAfter,proto3" json:"DeliverAfter,omitempty"` // Timestamp where item should be dequeue
	DpsAssignedUniqueId string `protobuf:"bytes,6,opt,name=DpsAssignedUniqueId,proto3" json:"DpsAssignedUniqueId,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{4}
}

func (x *Item) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Item) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Item) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Item) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Item) GetDeliverAfter() int32 {
	if x != nil {
		return x.DeliverAfter
	}
	return 0
}

func (x *Item) GetDpsAssignedUniqueId() string {
	if x != nil {
		return x.DpsAssignedUniqueId
	}
	return ""
}

type DequeueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DequeueTopic map[string]int32 `protobuf:"bytes,1,rep,name=DequeueTopic,proto3" json:"DequeueTopic,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *DequeueReq) Reset() {
	*x = DequeueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueReq) ProtoMessage() {}

func (x *DequeueReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueReq.ProtoReflect.Descriptor instead.
func (*DequeueReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{5}
}

func (x *DequeueReq) GetDequeueTopic() map[string]int32 {
	if x != nil {
		return x.DequeueTopic
	}
	return nil
}

type DequeueRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *DequeueRes) Reset() {
	*x = DequeueRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRes) ProtoMessage() {}

func (x *DequeueRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRes.ProtoReflect.Descriptor instead.
func (*DequeueRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{6}
}

func (x *DequeueRes) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic               string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	DpsAssignedUniqueId string `protobuf:"bytes,2,opt,name=DpsAssignedUniqueId,proto3" json:"DpsAssignedUniqueId,omitempty"`
}

func (x *AckReq) Reset() {
	*x = AckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReq) ProtoMessage() {}

func (x *AckReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReq.ProtoReflect.Descriptor instead.
func (*AckReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{7}
}

func (x *AckReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckReq) GetDpsAssignedUniqueId() string {
	if x != nil {
		return x.DpsAssignedUniqueId
	}
	return ""
}

type NAckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic               string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	DpsAssignedUniqueId string `protobuf:"bytes,2,opt,name=DpsAssignedUniqueId,proto3" json:"DpsAssignedUniqueId,omitempty"`
}

func (x *NAckReq) Reset() {
	*x = NAckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NAckReq) ProtoMessage() {}

func (x *NAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NAckReq.ProtoReflect.Descriptor instead.
func (*NAckReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{8}
}

func (x *NAckReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NAckReq) GetDpsAssignedUniqueId() string {
	if x != nil {
		return x.DpsAssignedUniqueId
	}
	return ""
}

var File_dps_server_proto protoreflect.FileDescriptor

var file_dps_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x22, 0x2e, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x09, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2f, 0x0a, 0x0a, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x21, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x3e, 0x0a, 0x0a, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xc4, 0x01, 0x0a, 0x04,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x72,
	0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0c,
	0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x41, 0x66, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0c, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x41, 0x66, 0x74, 0x65, 0x72,
	0x12, 0x30, 0x0a, 0x13, 0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x44,
	0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x49, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x65, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c,
	0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x1a, 0x3f, 0x0a, 0x11,
	0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x31, 0x0a,
	0x0a, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x70, 0x73,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x50, 0x0a, 0x06, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x30, 0x0a, 0x13, 0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55,
	0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x44,
	0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65,
	0x49, 0x64, 0x22, 0x51, 0x0a, 0x07, 0x4e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x30, 0x0a, 0x13, 0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x65, 0x64, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x13, 0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x32, 0x96, 0x02, 0x0a, 0x0a, 0x44, 0x70, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12,
	0x13, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73,
	0x68, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x17, 0x2e, 0x64, 0x70, 0x73,
	0x5f, 0x73, 0x72, 0x76, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x07, 0x44, 0x65, 0x71,
	0x75, 0x65, 0x75, 0x65, 0x12, 0x13, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x2e, 0x44,
	0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x64, 0x70, 0x73, 0x5f,
	0x73, 0x72, 0x76, 0x2e, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x2c, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x0f, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72,
	0x76, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73,
	0x72, 0x76, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2e,
	0x0a, 0x04, 0x4e, 0x41, 0x63, 0x6b, 0x12, 0x10, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76,
	0x2e, 0x4e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x73,
	0x72, 0x76, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0b,
	0x5a, 0x09, 0x2e, 0x2f, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dps_server_proto_rawDescOnce sync.Once
	file_dps_server_proto_rawDescData = file_dps_server_proto_rawDesc
)

func file_dps_server_proto_rawDescGZIP() []byte {
	file_dps_server_proto_rawDescOnce.Do(func() {
		file_dps_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_dps_server_proto_rawDescData)
	})
	return file_dps_server_proto_rawDescData
}

var file_dps_server_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_dps_server_proto_goTypes = []interface{}{
	(*CreateTopicReq)(nil), // 0: dps_pb.CreateTopicReq
	(*CommonRes)(nil),      // 1: dps_pb.CommonRes
	(*PublishReq)(nil),     // 2: dps_pb.PublishReq
	(*PublishRes)(nil),     // 3: dps_pb.PublishRes
	(*Item)(nil),           // 4: dps_pb.Item
	(*DequeueReq)(nil),     // 5: dps_pb.DequeueReq
	(*DequeueRes)(nil),     // 6: dps_pb.DequeueRes
	(*AckReq)(nil),         // 7: dps_pb.AckReq
	(*NAckReq)(nil),        // 8: dps_pb.NAckReq
	nil,                    // 9: dps_pb.DequeueReq.DequeueTopicEntry
}
var file_dps_server_proto_depIdxs = []int32{
	4, // 0: dps_pb.PublishReq.item:type_name -> dps_pb.Item
	9, // 1: dps_pb.DequeueReq.DequeueTopic:type_name -> dps_pb.DequeueReq.DequeueTopicEntry
	4, // 2: dps_pb.DequeueRes.items:type_name -> dps_pb.Item
	2, // 3: dps_pb.DpsService.Publish:input_type -> dps_pb.PublishReq
	0, // 4: dps_pb.DpsService.CreateTopic:input_type -> dps_pb.CreateTopicReq
	5, // 5: dps_pb.DpsService.Dequeue:input_type -> dps_pb.DequeueReq
	7, // 6: dps_pb.DpsService.Ack:input_type -> dps_pb.AckReq
	8, // 7: dps_pb.DpsService.NAck:input_type -> dps_pb.NAckReq
	3, // 8: dps_pb.DpsService.Publish:output_type -> dps_pb.PublishRes
	1, // 9: dps_pb.DpsService.CreateTopic:output_type -> dps_pb.CommonRes
	6, // 10: dps_pb.DpsService.Dequeue:output_type -> dps_pb.DequeueRes
	1, // 11: dps_pb.DpsService.Ack:output_type -> dps_pb.CommonRes
	1, // 12: dps_pb.DpsService.NAck:output_type -> dps_pb.CommonRes
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dps_server_proto_init() }
func file_dps_server_proto_init() {
	if File_dps_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dps_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NAckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dps_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dps_server_proto_goTypes,
		DependencyIndexes: file_dps_server_proto_depIdxs,
		MessageInfos:      file_dps_server_proto_msgTypes,
	}.Build()
	File_dps_server_proto = out.File
	file_dps_server_proto_rawDesc = nil
	file_dps_server_proto_goTypes = nil
	file_dps_server_proto_depIdxs = nil
}
