// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: dps_server.proto

package dps_pb

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopicActive int32

const (
	TopicActive_ACTIVE   TopicActive = 0
	TopicActive_INACTIVE TopicActive = 1
)

// Enum value maps for TopicActive.
var (
	TopicActive_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
	}
	TopicActive_value = map[string]int32{
		"ACTIVE":   0,
		"INACTIVE": 1,
	}
)

func (x TopicActive) Enum() *TopicActive {
	p := new(TopicActive)
	*p = x
	return p
}

func (x TopicActive) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TopicActive) Descriptor() protoreflect.EnumDescriptor {
	return file_dps_server_proto_enumTypes[0].Descriptor()
}

func (TopicActive) Type() protoreflect.EnumType {
	return &file_dps_server_proto_enumTypes[0]
}

func (x TopicActive) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TopicActive.Descriptor instead.
func (TopicActive) EnumDescriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{0}
}

type DeliverPolicy int32

const (
	DeliverPolicy_AT_LEAST_ONCE DeliverPolicy = 0
	DeliverPolicy_AT_MOST_ONCE  DeliverPolicy = 1
)

// Enum value maps for DeliverPolicy.
var (
	DeliverPolicy_name = map[int32]string{
		0: "AT_LEAST_ONCE",
		1: "AT_MOST_ONCE",
	}
	DeliverPolicy_value = map[string]int32{
		"AT_LEAST_ONCE": 0,
		"AT_MOST_ONCE":  1,
	}
)

func (x DeliverPolicy) Enum() *DeliverPolicy {
	p := new(DeliverPolicy)
	*p = x
	return p
}

func (x DeliverPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliverPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_dps_server_proto_enumTypes[1].Descriptor()
}

func (DeliverPolicy) Type() protoreflect.EnumType {
	return &file_dps_server_proto_enumTypes[1]
}

func (x DeliverPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliverPolicy.Descriptor instead.
func (DeliverPolicy) EnumDescriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{1}
}

type CreateTopicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicName     string        `protobuf:"bytes,1,opt,name=TopicName,proto3" json:"TopicName,omitempty"`
	DeliverPolicy DeliverPolicy `protobuf:"varint,2,opt,name=DeliverPolicy,proto3,enum=dps_pb.DeliverPolicy" json:"DeliverPolicy,omitempty"`
}

func (x *CreateTopicReq) Reset() {
	*x = CreateTopicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicReq) ProtoMessage() {}

func (x *CreateTopicReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicReq.ProtoReflect.Descriptor instead.
func (*CreateTopicReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTopicReq) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *CreateTopicReq) GetDeliverPolicy() DeliverPolicy {
	if x != nil {
		return x.DeliverPolicy
	}
	return DeliverPolicy_AT_LEAST_ONCE
}

type CreateTopicRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicId        string      `protobuf:"bytes,1,opt,name=TopicId,proto3" json:"TopicId,omitempty"`
	Name           string      `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Active         TopicActive `protobuf:"varint,3,opt,name=Active,proto3,enum=dps_pb.TopicActive" json:"Active,omitempty"`
	DeliveryPolicy string      `protobuf:"bytes,4,opt,name=DeliveryPolicy,proto3" json:"DeliveryPolicy,omitempty"`
}

func (x *CreateTopicRes) Reset() {
	*x = CreateTopicRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTopicRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRes) ProtoMessage() {}

func (x *CreateTopicRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRes.ProtoReflect.Descriptor instead.
func (*CreateTopicRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTopicRes) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *CreateTopicRes) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTopicRes) GetActive() TopicActive {
	if x != nil {
		return x.Active
	}
	return TopicActive_ACTIVE
}

func (x *CreateTopicRes) GetDeliveryPolicy() string {
	if x != nil {
		return x.DeliveryPolicy
	}
	return ""
}

type CommonRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *CommonRes) Reset() {
	*x = CommonRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommonRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRes) ProtoMessage() {}

func (x *CommonRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRes.ProtoReflect.Descriptor instead.
func (*CommonRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{2}
}

func (x *CommonRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CommonRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Item `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *PublishReq) Reset() {
	*x = PublishReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishReq) ProtoMessage() {}

func (x *PublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishReq.ProtoReflect.Descriptor instead.
func (*PublishReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{3}
}

func (x *PublishReq) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type PublishRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  int32  `protobuf:"varint,1,opt,name=Status,proto3" json:"Status,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *PublishRes) Reset() {
	*x = PublishRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRes) ProtoMessage() {}

func (x *PublishRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRes.ProtoReflect.Descriptor instead.
func (*PublishRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRes) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PublishRes) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TopicId      string `protobuf:"bytes,1,opt,name=TopicId,proto3" json:"TopicId,omitempty"`
	Priority     int32  `protobuf:"varint,2,opt,name=Priority,proto3" json:"Priority,omitempty"`         // Lower number mean higher priority
	Payload      []byte `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`            // immutable binary blob. Feel free to put what ever u want
	Metadata     []byte `protobuf:"bytes,4,opt,name=Metadata,proto3" json:"Metadata,omitempty"`          // mutable binary blob. Feel free to put what ever u want
	DeliverAfter int32  `protobuf:"varint,5,opt,name=DeliverAfter,proto3" json:"DeliverAfter,omitempty"` // Timestamp where item should be dequeue
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{5}
}

func (x *Item) GetTopicId() string {
	if x != nil {
		return x.TopicId
	}
	return ""
}

func (x *Item) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Item) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Item) GetMetadata() []byte {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Item) GetDeliverAfter() int32 {
	if x != nil {
		return x.DeliverAfter
	}
	return 0
}

type DequeueReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DequeueTopic map[string]int32 `protobuf:"bytes,1,rep,name=DequeueTopic,proto3" json:"DequeueTopic,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *DequeueReq) Reset() {
	*x = DequeueReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueReq) ProtoMessage() {}

func (x *DequeueReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueReq.ProtoReflect.Descriptor instead.
func (*DequeueReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{6}
}

func (x *DequeueReq) GetDequeueTopic() map[string]int32 {
	if x != nil {
		return x.DequeueTopic
	}
	return nil
}

type DequeueRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *DequeueRes) Reset() {
	*x = DequeueRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DequeueRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRes) ProtoMessage() {}

func (x *DequeueRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRes.ProtoReflect.Descriptor instead.
func (*DequeueRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{7}
}

func (x *DequeueRes) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type AckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic               string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	DpsAssignedUniqueId string `protobuf:"bytes,2,opt,name=DpsAssignedUniqueId,proto3" json:"DpsAssignedUniqueId,omitempty"`
}

func (x *AckReq) Reset() {
	*x = AckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckReq) ProtoMessage() {}

func (x *AckReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckReq.ProtoReflect.Descriptor instead.
func (*AckReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{8}
}

func (x *AckReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckReq) GetDpsAssignedUniqueId() string {
	if x != nil {
		return x.DpsAssignedUniqueId
	}
	return ""
}

type NAckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic               string `protobuf:"bytes,1,opt,name=Topic,proto3" json:"Topic,omitempty"`
	DpsAssignedUniqueId string `protobuf:"bytes,2,opt,name=DpsAssignedUniqueId,proto3" json:"DpsAssignedUniqueId,omitempty"`
}

func (x *NAckReq) Reset() {
	*x = NAckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NAckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NAckReq) ProtoMessage() {}

func (x *NAckReq) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NAckReq.ProtoReflect.Descriptor instead.
func (*NAckReq) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{9}
}

func (x *NAckReq) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NAckReq) GetDpsAssignedUniqueId() string {
	if x != nil {
		return x.DpsAssignedUniqueId
	}
	return ""
}

type GetActiveTopicsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topics []*Topic `protobuf:"bytes,1,rep,name=Topics,proto3" json:"Topics,omitempty"`
}

func (x *GetActiveTopicsRes) Reset() {
	*x = GetActiveTopicsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveTopicsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveTopicsRes) ProtoMessage() {}

func (x *GetActiveTopicsRes) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveTopicsRes.ProtoReflect.Descriptor instead.
func (*GetActiveTopicsRes) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{10}
}

func (x *GetActiveTopicsRes) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type Topic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name           string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DeliveryPolicy string `protobuf:"bytes,3,opt,name=DeliveryPolicy,proto3" json:"DeliveryPolicy,omitempty"`
}

func (x *Topic) Reset() {
	*x = Topic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dps_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_dps_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_dps_server_proto_rawDescGZIP(), []int{11}
}

func (x *Topic) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Topic) GetDeliveryPolicy() string {
	if x != nil {
		return x.DeliveryPolicy
	}
	return ""
}

var File_dps_server_proto protoreflect.FileDescriptor

var file_dps_server_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x70, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x6f,
	0x70, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x69, 0x76,
	0x65, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15,
	0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x52, 0x0d, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x22, 0x93, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x6c, 0x69,
	0x76, 0x65, 0x72, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x22, 0x3d, 0x0a, 0x09, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x2e, 0x0a, 0x0a, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x71, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x3e, 0x0a, 0x0a, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x04, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x50, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x50, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22,
	0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x41, 0x66, 0x74, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x41, 0x66, 0x74,
	0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x48, 0x0a, 0x0c, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62,
	0x2e, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x44, 0x65, 0x71, 0x75,
	0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x44,
	0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x1a, 0x3f, 0x0a, 0x11, 0x44,
	0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x30, 0x0a, 0x0a,
	0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x70, 0x73, 0x5f,
	0x70, 0x62, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x50,
	0x0a, 0x06, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x30,
	0x0a, 0x13, 0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x44, 0x70, 0x73,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64,
	0x22, 0x51, 0x0a, 0x07, 0x4e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x70, 0x69,
	0x63, 0x12, 0x30, 0x0a, 0x13, 0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13,
	0x44, 0x70, 0x73, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x55, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06, 0x54, 0x6f, 0x70,
	0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x70, 0x73, 0x5f,
	0x70, 0x62, 0x2e, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x06, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73,
	0x22, 0x53, 0x0a, 0x05, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x2a, 0x27, 0x0a, 0x0b, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x2a, 0x34,
	0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x50, 0x6f, 0x6c, 0x69, 0x63, 0x79, 0x12,
	0x11, 0x0a, 0x0d, 0x41, 0x54, 0x5f, 0x4c, 0x45, 0x41, 0x53, 0x54, 0x5f, 0x4f, 0x4e, 0x43, 0x45,
	0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x41, 0x54, 0x5f, 0x4d, 0x4f, 0x53, 0x54, 0x5f, 0x4f, 0x4e,
	0x43, 0x45, 0x10, 0x01, 0x32, 0xda, 0x02, 0x0a, 0x0a, 0x44, 0x70, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x12,
	0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x52,
	0x65, 0x71, 0x1a, 0x12, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x73, 0x68, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x3f, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63,
	0x12, 0x16, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70,
	0x62, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x12, 0x33, 0x0a, 0x07, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x12, 0x12, 0x2e,
	0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x71, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x12, 0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x71, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x0e,
	0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x04, 0x4e, 0x41, 0x63, 0x6b, 0x12, 0x0f, 0x2e, 0x64, 0x70,
	0x73, 0x5f, 0x70, 0x62, 0x2e, 0x4e, 0x41, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x64,
	0x70, 0x73, 0x5f, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x64, 0x70, 0x73, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dps_server_proto_rawDescOnce sync.Once
	file_dps_server_proto_rawDescData = file_dps_server_proto_rawDesc
)

func file_dps_server_proto_rawDescGZIP() []byte {
	file_dps_server_proto_rawDescOnce.Do(func() {
		file_dps_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_dps_server_proto_rawDescData)
	})
	return file_dps_server_proto_rawDescData
}

var file_dps_server_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dps_server_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_dps_server_proto_goTypes = []interface{}{
	(TopicActive)(0),           // 0: dps_pb.TopicActive
	(DeliverPolicy)(0),         // 1: dps_pb.DeliverPolicy
	(*CreateTopicReq)(nil),     // 2: dps_pb.CreateTopicReq
	(*CreateTopicRes)(nil),     // 3: dps_pb.CreateTopicRes
	(*CommonRes)(nil),          // 4: dps_pb.CommonRes
	(*PublishReq)(nil),         // 5: dps_pb.PublishReq
	(*PublishRes)(nil),         // 6: dps_pb.PublishRes
	(*Item)(nil),               // 7: dps_pb.Item
	(*DequeueReq)(nil),         // 8: dps_pb.DequeueReq
	(*DequeueRes)(nil),         // 9: dps_pb.DequeueRes
	(*AckReq)(nil),             // 10: dps_pb.AckReq
	(*NAckReq)(nil),            // 11: dps_pb.NAckReq
	(*GetActiveTopicsRes)(nil), // 12: dps_pb.GetActiveTopicsRes
	(*Topic)(nil),              // 13: dps_pb.Topic
	nil,                        // 14: dps_pb.DequeueReq.DequeueTopicEntry
	(*empty.Empty)(nil),        // 15: google.protobuf.Empty
}
var file_dps_server_proto_depIdxs = []int32{
	1,  // 0: dps_pb.CreateTopicReq.DeliverPolicy:type_name -> dps_pb.DeliverPolicy
	0,  // 1: dps_pb.CreateTopicRes.Active:type_name -> dps_pb.TopicActive
	7,  // 2: dps_pb.PublishReq.item:type_name -> dps_pb.Item
	14, // 3: dps_pb.DequeueReq.DequeueTopic:type_name -> dps_pb.DequeueReq.DequeueTopicEntry
	7,  // 4: dps_pb.DequeueRes.items:type_name -> dps_pb.Item
	13, // 5: dps_pb.GetActiveTopicsRes.Topics:type_name -> dps_pb.Topic
	5,  // 6: dps_pb.DpsService.Publish:input_type -> dps_pb.PublishReq
	15, // 7: dps_pb.DpsService.GetActiveTopics:input_type -> google.protobuf.Empty
	2,  // 8: dps_pb.DpsService.CreateTopic:input_type -> dps_pb.CreateTopicReq
	8,  // 9: dps_pb.DpsService.Dequeue:input_type -> dps_pb.DequeueReq
	10, // 10: dps_pb.DpsService.Ack:input_type -> dps_pb.AckReq
	11, // 11: dps_pb.DpsService.NAck:input_type -> dps_pb.NAckReq
	6,  // 12: dps_pb.DpsService.Publish:output_type -> dps_pb.PublishRes
	12, // 13: dps_pb.DpsService.GetActiveTopics:output_type -> dps_pb.GetActiveTopicsRes
	3,  // 14: dps_pb.DpsService.CreateTopic:output_type -> dps_pb.CreateTopicRes
	9,  // 15: dps_pb.DpsService.Dequeue:output_type -> dps_pb.DequeueRes
	4,  // 16: dps_pb.DpsService.Ack:output_type -> dps_pb.CommonRes
	4,  // 17: dps_pb.DpsService.NAck:output_type -> dps_pb.CommonRes
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_dps_server_proto_init() }
func file_dps_server_proto_init() {
	if File_dps_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dps_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTopicRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommonRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DequeueRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NAckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveTopicsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dps_server_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Topic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dps_server_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dps_server_proto_goTypes,
		DependencyIndexes: file_dps_server_proto_depIdxs,
		EnumInfos:         file_dps_server_proto_enumTypes,
		MessageInfos:      file_dps_server_proto_msgTypes,
	}.Build()
	File_dps_server_proto = out.File
	file_dps_server_proto_rawDesc = nil
	file_dps_server_proto_goTypes = nil
	file_dps_server_proto_depIdxs = nil
}
